### ISSUE TITLE
Hide external symbols in RoboVM libs

### ISSUE THREAD

**Issue by tomfisher** [robovm/robovm#795]
As discussed as in the [forum](https://groups.google.com/forum/#!topic/robovm/93Wg7iGwsaQ)

**Comment by ntherning** [comment]
I think we have fixed this now. Please try with the latest nightly build: http://docs.robovm.com/advanced-topics/nightlies.html and let us know if it works.

**Comment by ntherning** [comment]
We only fixup `librobovm-rt.a` on Darwin. We need to do the same on Linux and there are still symbols in the other VM libs that could cause conflicts though much less likely than for `librobovm-rt.a`.

**Comment by tomfisher** [comment]
OK, I'll try that.

**Comment by tomfisher** [comment]
It does not resolve the issue since the duplicated symbolics for SHA related example  are still in the static lib and can be listed using the following command:
```
nm ./vm/target/build/macosx-x86_64-release/rt/librobovm-rt.a | grep SHA1
000000000024407f t _PKCS5_PBKDF2_HMAC_SHA1
000000000026cca0 t _SHA1
0000000000471b40 b _SHA1.m
000000000026de9e t _SHA1_Final
000000000026df9b t _SHA1_Init
000000000026de8f t _SHA1_Transform
000000000026cd0e t _SHA1_Update
0000000000344b60 s _SHA1_version

```

In addition, the new build script seems to try to fetch the same 3rd party repositories more than once e.g extgc, which really takes an appreciable time.

**Comment by tomfisher** [comment]
I built the lib with the source code directly rather than those bound in the downloaded jar.

**Comment by ntherning** [comment]
Did you try to build your app against it? The symbols are now local which means that they shouldn't collide with global symbols with the same name in other libs/object files linked into the app (this is what the lowercase `t`, `b`, `s`, etc mean). To list externally visible symbols using `nm` you have to add the `-g` option:

```
nm -g ./vm/target/build/macosx-x86_64-release/rt/librobovm-rt.a | grep SHA1
```

**Comment by tomfisher** [comment]
Sorry not to notice that. It works now
