### ISSUE TITLE
No @Marshaler found...

### ISSUE THREAD

**Issue by deadpixelsociety** [robovm/robovm#977]
Upgraded my project to use RoboVM 1.2 and downloaded the IDEA Plugin 1.2 nightly. Compiling fails when it hits my Main.app class because of the 'performFetch' method I have implemented for my Background Fetch. If I comment that method block out it compiles fine.

[DEBUG] Compiling com.ontime.mobile.Main (ios x86 release)
[ERROR] Couldn't compile app
java.lang.IllegalArgumentException: No @Marshaler found for parameter 4 of @Callback method <com.ontime.mobile.Main: void $cb$application$performFetchWithCompletionHandler$(com.ontime.mobile.Main,org.robovm.objc.Selector,org.robovm.apple.uikit.UIApplication,org.robovm.objc.block.VoidBlock1)>
	at org.robovm.compiler.MarshalerLookup.findMarshalerMethod(MarshalerLookup.java:169)
	at org.robovm.compiler.BroMethodCompiler.getParameterType(BroMethodCompiler.java:514)
	at org.robovm.compiler.BroMethodCompiler.getBridgeOrCallbackFunctionType(BroMethodCompiler.java:540)
	at org.robovm.compiler.BroMethodCompiler.getCallbackFunctionType(BroMethodCompiler.java:527)
	at org.robovm.compiler.CallbackMethodCompiler.compileCallback(CallbackMethodCompiler.java:175)
	at org.robovm.compiler.CallbackMethodCompiler.doCompile(CallbackMethodCompiler.java:69)
	at org.robovm.compiler.AbstractMethodCompiler.compile(AbstractMethodCompiler.java:73)
	at org.robovm.compiler.ClassCompiler.callbackMethod(ClassCompiler.java:1287)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:749)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:287)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:241)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:330)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:374)
	at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:60)
	at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)

**Comment by ntherning** [comment]
We need to see the source code for the class which causes this exception.

**Comment by deadpixelsociety** [comment]
```java
package com.ontime.mobile;

import com.ontime.mobile.data.OnTimeFetcher;
import com.ontime.mobile.sql.OnTimeDatabase;
import com.ontime.mobile.sql.OnTimeDatabaseHelper;
import org.robovm.apple.foundation.NSAutoreleasePool;
import org.robovm.apple.uikit.UIApplication;
import org.robovm.apple.uikit.UIApplicationDelegateAdapter;
import org.robovm.apple.uikit.UIApplicationLaunchOptions;
import org.robovm.apple.uikit.UIBackgroundFetchResult;
import org.robovm.objc.annotation.Block;
import org.robovm.objc.block.VoidBlock1;

public class OnTimeMobile extends UIApplicationDelegateAdapter {

    public static void main(String[] args) {
        try (NSAutoreleasePool pool = new NSAutoreleasePool()) {
            UIApplication.main(args, null, OnTimeMobile.class);
        }
    }

    @Override
    public boolean didFinishLaunching(UIApplication application, UIApplicationLaunchOptions launchOptions) {
        UIApplication.getSharedApplication()
                     .setMinimumBackgroundFetchInterval(UIApplication.getBackgroundFetchIntervalMinimum());

        return true;
    }

    @Override
    public void performFetch(final UIApplication application, @Block final VoidBlock1<UIBackgroundFetchResult> completionHandler) {
        super.performFetch(application, completionHandler);

        new OnTimeFetcher().fetch(completionHandler);
    }

    @Override
    public boolean willFinishLaunching(final UIApplication application, final UIApplicationLaunchOptions launchOptions) {
        OnTimeDatabase.getInstance().init(OnTimeDatabaseHelper.getInstance().getConnectionSource());

        return super.willFinishLaunching(application, launchOptions);
    }
}
```
The performFetch method.

Tried it without the @Block annotation on the VoidBlock1 parameter (the default way when it's overriden) and added the @Block to match the delegate's signature afterwards. Both ways fail to compile unless that entire method block is commented out.

**Comment by ntherning** [comment]
Thanks, I could reproduce this. It's a regression which appeared in the latest release due to the file size optimizations we did. I just pushed a fix. Please try with the next nightly build (20150510) and see if that fixes your problem: http://docs.robovm.com/advanced-topics/nightlies.html.

**Comment by deadpixelsociety** [comment]
Was able to test this just now. Cleared my Gradle caches along with both .robovm directories and refreshed my project to pull the latest available SNAPSHOTs (looks like it was pulling a 20150510 build. Guess 20150511 isn't available yet). The error remains unfortunately.

Is there a way to determine exactly which version of the RoboVM jars were downloaded? IntelliJ just references them as '1.2.1-SNAPSHOT'. I did see the 20150510 build in the Gradle info as it was refreshing, but who knows?

**Comment by badlogic** [comment]
Could you build the app via Gradle on the CLI and see if that works?

IntelliJ doesn't give you a way to show where the dependency's file is
located i'm afraid :/

**Comment by deadpixelsociety** [comment]
More testing today. Uninstalled the plugin, cleared all caches, reinstalled, refreshed, verified it was pulling newest nightlies. Build succeeded w/ fetch method included. Looks like this is resolved!

**Comment by BlueRiverInteractive** [comment]
Hey, that's awesome! 

Feel free to close this issue if it's fixed.
